version: "3.9"

services:

  postgres:
    image: postgres:16
    container_name: bizee

    restart: unless-stopped

    environment:
      POSTGRES_DB: bizee
      POSTGRES_USER: bizee
      POSTGRES_PASSWORD: bizee

    ports:
      - "5432:5432"

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d bizee"]
      interval: 10s
      timeout: 5s
      retries: 10

  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    container_name: bizee-rabbitmq

    restart: unless-stopped

    environment:
      RABBITMQ_DEFAULT_USER: bizee
      RABBITMQ_DEFAULT_PASS: bizee

    ports:
      - "5672:5672"
      - "15672:15672"

    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  postgres-data: