-- Flyway migration for PostgreSQL
-- File: V1__create_and_seed_users_companies_registered_agents.sql

BEGIN;

-- =========================================================
-- 1. TABLES
-- =========================================================

CREATE TABLE users (
                       id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       name        VARCHAR(150) NOT NULL,
                       email       VARCHAR(255) NOT NULL UNIQUE,
                       password    VARCHAR(255) NOT NULL,
                       created_at  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                       updated_at  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE registered_agents (
                                   id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                   state       CHAR(2) NOT NULL,
                                   name        VARCHAR(150) NOT NULL,
                                   email       VARCHAR(255) NOT NULL UNIQUE,
                                   capacity    INTEGER NOT NULL CHECK (capacity BETWEEN 5 AND 15),
                                   created_at  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                   updated_at  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                   CONSTRAINT uq_registered_agents_state_email UNIQUE (state, email)
);

CREATE TABLE companies (
                           id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           user_id                 BIGINT NOT NULL,
                           name                    VARCHAR(200) NOT NULL,
                           state                   CHAR(2) NOT NULL,
                           registered_agent_type   VARCHAR(30) NOT NULL,
                           registered_agent_id     BIGINT NOT NULL,
                           created_at              TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                           updated_at              TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

                           CONSTRAINT fk_companies_user
                               FOREIGN KEY (user_id) REFERENCES users(id),

                           CONSTRAINT chk_companies_registered_agent_type
                               CHECK (registered_agent_type IN ('user', 'registered_agent'))
);


-- =========================================================
-- 3. USERS: EXACTLY 5 RECORDS
-- Demo auth: password plaintext value equals the user's email, stored as a BCrypt hash.
-- =========================================================

INSERT INTO users (id, name, email, password)
VALUES
    (1, 'Alice Johnson', 'alice.johnson@example.com', '$2a$10$QKSzh34IUMQS1W63OwZR.uU/UOOe1siUzg5zZQGdVH/HOfeChmD.G'),
    (2, 'Brian Smith',  'brian.smith@example.com',   '$2a$10$QnrfirMw9Wi.R8aTw2670Oo4X0ADXM07.QwB5v4u0olNmjT..z5QW'),
    (3, 'Carla Davis',  'carla.davis@example.com',   '$2a$10$sI1uWbYK9smYzcXe7RA3XeBshYLD/8iEh6IsonrYZRRUuuuT74E/W'),
    (4, 'Daniel Wilson','daniel.wilson@example.com', '$2a$10$aXhJJDooKZ5jfApNv1OSXuuAilyWgyJ.sEN0o7ZX0hlt7/lxfgF2i'),
    (5, 'Emma Brown',   'emma.brown@example.com',    '$2a$10$Ar3DHGel7RMpFrdkg7Y7C.G2B9UhlW6V8k0THB7PNQT.3/zBoRH7i');

-- =========================================================
-- 4. REGISTERED AGENTS: EXACTLY 51 RECORDS
--
-- Rules:
-- - 2 agents in California (CA)
-- - 2 agents in Texas (TX)
-- - 0 agents in Illinois (IL)
-- - 1 agent in each of the other 47 states
--
-- Total: 47 + 2 + 2 = 51
-- Capacity is deterministic and remains between 5 and 15.
-- =========================================================

WITH states(state, state_name) AS (
    VALUES
        ('AL', 'Alabama'),
        ('AK', 'Alaska'),
        ('AZ', 'Arizona'),
        ('AR', 'Arkansas'),
        ('CA', 'California'),
        ('CO', 'Colorado'),
        ('CT', 'Connecticut'),
        ('DE', 'Delaware'),
        ('FL', 'Florida'),
        ('GA', 'Georgia'),
        ('HI', 'Hawaii'),
        ('ID', 'Idaho'),
        -- Illinois intentionally excluded
        ('IN', 'Indiana'),
        ('IA', 'Iowa'),
        ('KS', 'Kansas'),
        ('KY', 'Kentucky'),
        ('LA', 'Louisiana'),
        ('ME', 'Maine'),
        ('MD', 'Maryland'),
        ('MA', 'Massachusetts'),
        ('MI', 'Michigan'),
        ('MN', 'Minnesota'),
        ('MS', 'Mississippi'),
        ('MO', 'Missouri'),
        ('MT', 'Montana'),
        ('NE', 'Nebraska'),
        ('NV', 'Nevada'),
        ('NH', 'New Hampshire'),
        ('NJ', 'New Jersey'),
        ('NM', 'New Mexico'),
        ('NY', 'New York'),
        ('NC', 'North Carolina'),
        ('ND', 'North Dakota'),
        ('OH', 'Ohio'),
        ('OK', 'Oklahoma'),
        ('OR', 'Oregon'),
        ('PA', 'Pennsylvania'),
        ('RI', 'Rhode Island'),
        ('SC', 'South Carolina'),
        ('SD', 'South Dakota'),
        ('TN', 'Tennessee'),
        ('TX', 'Texas'),
        ('UT', 'Utah'),
        ('VT', 'Vermont'),
        ('VA', 'Virginia'),
        ('WA', 'Washington'),
        ('WV', 'West Virginia'),
        ('WI', 'Wisconsin'),
        ('WY', 'Wyoming')
),
     base_agents AS (
         SELECT
             ROW_NUMBER() OVER (ORDER BY state)::BIGINT AS id,
             state,
             state_name || ' Registered Agent' AS name,
             'agent.' || LOWER(state) || '@example.com' AS email,
             5 + ((ROW_NUMBER() OVER (ORDER BY state) - 1) % 11)::INTEGER AS capacity
FROM states
    )
INSERT INTO registered_agents (id, state, name, email, capacity)
SELECT id, state, name, email, capacity
FROM base_agents
ORDER BY id;

-- Add the second California and Texas agents.
INSERT INTO registered_agents (id, state, name, email, capacity)
VALUES
    (50, 'CA', 'California Registered Agent 2', 'agent.ca.2@example.com', 12),
    (51, 'TX', 'Texas Registered Agent 2',      'agent.tx.2@example.com', 10);

-- =========================================================
-- 5. COMPANIES: 10 RECORDS
-- Each of the 5 users owns 2 companies.
-- =========================================================

INSERT INTO companies (
    id,
    user_id,
    name,
    state,
    registered_agent_type,
    registered_agent_id
)
VALUES
    (1,  1, 'Alice Consulting LLC',       'CA', 'user',             1),
    (2,  1, 'Golden State Analytics Inc', 'CA', 'registered_agent', (SELECT id FROM registered_agents WHERE email = 'agent.ca@example.com')),

    (3,  2, 'Brian Logistics LLC',        'TX', 'user',             2),
    (4,  2, 'Lone Star Systems Inc',      'TX', 'registered_agent', (SELECT id FROM registered_agents WHERE email = 'agent.tx.2@example.com')),

    (5,  3, 'Carla Retail Group LLC',     'FL', 'user',             3),
    (6,  3, 'Sunshine Commerce Inc',      'FL', 'registered_agent', (SELECT id FROM registered_agents WHERE email = 'agent.fl@example.com')),

    (7,  4, 'Daniel Software LLC',        'NY', 'user',             4),
    (8,  4, 'Empire Cloud Services Inc',  'NY', 'registered_agent', (SELECT id FROM registered_agents WHERE email = 'agent.ny@example.com')),

    (9,  5, 'Emma Manufacturing LLC',     'WA', 'user',             5),
    (10, 5, 'Pacific Automation Inc',     'WA', 'registered_agent', (SELECT id FROM registered_agents WHERE email = 'agent.wa@example.com'));

-- =========================================================
-- =========================================================

DO $$
DECLARE
total_users               INTEGER;
    total_companies           INTEGER;
    users_without_companies   INTEGER;
    total_agents              INTEGER;
    california_agents         INTEGER;
    texas_agents              INTEGER;
    illinois_agents           INTEGER;
    invalid_other_states      INTEGER;
BEGIN
SELECT COUNT(*) INTO total_users
FROM users;

SELECT COUNT(*) INTO total_companies
FROM companies;

SELECT COUNT(*) INTO users_without_companies
FROM users u
WHERE NOT EXISTS (
    SELECT 1
    FROM companies c
    WHERE c.user_id = u.id
);

SELECT COUNT(*) INTO total_agents
FROM registered_agents;

SELECT COUNT(*) INTO california_agents
FROM registered_agents
WHERE state = 'CA';

SELECT COUNT(*) INTO texas_agents
FROM registered_agents
WHERE state = 'TX';

SELECT COUNT(*) INTO illinois_agents
FROM registered_agents
WHERE state = 'IL';

SELECT COUNT(*) INTO invalid_other_states
FROM (
         SELECT state, COUNT(*) AS agent_count
         FROM registered_agents
         WHERE state NOT IN ('CA', 'TX', 'IL')
         GROUP BY state
         HAVING COUNT(*) <> 1
     ) invalid_states;

IF total_users <> 5 THEN
        RAISE EXCEPTION 'Expected 5 users, found %', total_users;
END IF;

    IF total_companies < 5 THEN
        RAISE EXCEPTION 'Expected at least 5 companies, found %', total_companies;
END IF;

    IF users_without_companies <> 0 THEN
        RAISE EXCEPTION
            'Every user must have at least one company; users without companies: %',
            users_without_companies;
END IF;

    IF total_agents <> 51 THEN
        RAISE EXCEPTION 'Expected 51 registered agents, found %', total_agents;
END IF;

    IF california_agents <> 2 THEN
        RAISE EXCEPTION
            'Expected 2 California agents, found %',
            california_agents;
END IF;

    IF texas_agents <> 2 THEN
        RAISE EXCEPTION
            'Expected 2 Texas agents, found %',
            texas_agents;
END IF;

    IF illinois_agents <> 0 THEN
        RAISE EXCEPTION
            'Expected 0 Illinois agents, found %',
            illinois_agents;
END IF;

    IF invalid_other_states <> 0 THEN
        RAISE EXCEPTION
            'Every state other than CA, TX and IL must have exactly one agent';
END IF;
END;
$$;

COMMIT;